variables:
  GIT_SUBMODULE_STRATEGY: normal

stages:
  - build-and-test
  - unit-tests

build-job:
  stage: build-and-test
  image: openjdk:14-jdk-slim
  script:
    - chmod +x ./gradlew
    - ./gradlew build

unit-testing-job:
  stage: unit-tests
  image: openjdk:14-jdk-slim
  script:
    - chmod +x ./gradlew
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml